### ISSUE TITLE
Symmetric Encryption

### ISSUE THREAD

**Issue by shreyaraghavendra** [akarody/ISTE_NeuroCrypto#2]
1. Generate ciphertext from Alice, that is fed into Bob and Eve.
2. Generate plaintext generated from Bob and Eve.
Use the NN models created to obtain the convolved message.

What is symmetric encryption?
The same private key is fed to both parties, which they use to encrypt and decrypt their message. In asymmetric encryption or public key cryptography, there are two private keys known only to the users, and a public key that may be disseminated widely.

**Comment by hrithikbhat019** [comment]
I have generated ciphertext from Alice and generated the output messages from Bob and Eve and uploaded the file to master.
