### ISSUE TITLE
Artificially creating a dataset

### ISSUE THREAD

**Issue by shreyaraghavendra** [akarody/ISTE_NeuroCrypto#3]
The data-set here is a pair of vectors to represent message and key having random bit values i.e 0 and 1, But 0 is never a good option to be given as a input to a neural network because it represents absence of a signal , so lets just encode 0 to -1 and 1 to 1.

**Comment by mrushad** [comment]
Created dataset with random 0/1 values.
Created pull request and merged file to master.
