### ISSUE TITLE
Loss function for Alice and Bob

### ISSUE THREAD

**Issue by shreyaraghavendra** [akarody/ISTE_NeuroCrypto#4]
Here, we introduce the adversarial nature- minimizing the error in number of bits, where Bob learns to reconstruct original message using the ciphertext and key might lead to Alice passing the original message itself as ciphertext to Bob. To ensure that that doesn't happen, we introduce a loss replicating Eve as an eavesdropper. In short, better the Eve gets at breaking their encryption bigger Alice-Bob’s loss gets. 

![image](https://user-images.githubusercontent.com/56431616/67688917-95933380-f9c0-11e9-81a0-cc9c96a7ef7f.png)

L1 and L2 are two loss functions in machine learning which are used to minimize the error.
L1 Loss function stands for Least Absolute Deviations. Also known as LAD.
L1 Loss Function is used to minimize the error which is the sum of the all the absolute differences between the true value and the predicted value.

![image](https://user-images.githubusercontent.com/56431616/67688613-23225380-f9c0-11e9-970a-488bfdde6d98.png)

**Comment by ArjunAnil2000** [comment]
I've done the loss function for Alice and Bob, created a pull request on the master and merged it.
